# Generated by Django 5.2.6 on 2025-11-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('user_objects', '0003_alter_userobject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_objects.userobject', verbose_name='Объект пользователя'),
        ),
    ]
