# Generated by Django 5.2.6 on 2025-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsandacts',
            name='tip',
        ),
        migrations.AddField(
            model_name='journalsandacts',
            name='type',
            field=models.CharField(blank=True, choices=[('estimate', 'Смета'), ('act', 'Акт'), ('form', 'Форма')], max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
