# Generated by Django 5.2.6 on 2025-12-02 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_journalsandacts_tip_journalsandacts_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='bill_documents/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_documents', to='documents.bills')),
            ],
            options={
                'verbose_name': 'Документ счета',
                'verbose_name_plural': 'Документы счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAndActDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='journal_and_act_documents/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('journal_and_act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_and_act_documents', to='documents.journalsandacts')),
            ],
            options={
                'verbose_name': 'Документ журнала и акта',
                'verbose_name_plural': 'Документы журнала и акта',
                'ordering': ['-created_at'],
            },
        ),
    ]
