# Generated by Django 5.2.6 on 2025-12-02 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_billdocuments_journalandactdocuments'),
        ('user_objects', '0003_alter_userobject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['user', '-created_at'], name='bills_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['object_id', '-created_at'], name='bills_object_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['status', '-created_at'], name='bills_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['object_id', 'user'], name='bills_object_user_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsandacts',
            index=models.Index(fields=['user', '-created_at'], name='journals_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsandacts',
            index=models.Index(fields=['object_id', '-created_at'], name='journals_object_created_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsandacts',
            index=models.Index(fields=['object_id', 'user'], name='journals_object_user_idx'),
        ),
    ]
