# Generated by Django 5.2.6 on 2025-11-14 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название объекта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес объекта')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер')),
                ('number_of_fire_extinguishing_systems', models.IntegerField(blank=True, null=True, verbose_name='Кол-во систем пожаротушения')),
                ('status', models.CharField(blank=True, choices=[('active', 'Активный'), ('pending', 'Ожидание'), ('completed', 'Завершенный'), ('cancelled', 'Отмененный'), ('on_hold', 'На паузе')], default='pending', max_length=255, null=True, verbose_name='Статус объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объект пользователя',
                'verbose_name_plural': 'Объекты пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserObjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_documents', to=settings.AUTH_USER_MODEL)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_documents', to='user_objects.userobject')),
            ],
            options={
                'verbose_name': 'Документ объекта пользователя',
                'verbose_name_plural': 'Документы объектов пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserObjectDocumentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='user_objects/documents/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_object_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_document_items', to='user_objects.userobjectdocuments')),
            ],
            options={
                'verbose_name': 'Элемент документа объекта пользователя',
                'verbose_name_plural': 'Элементы документов объектов пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserObjectWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_workers', to=settings.AUTH_USER_MODEL)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_workers', to='user_objects.userobject')),
            ],
            options={
                'verbose_name': 'Работник объекта пользователя',
                'verbose_name_plural': 'Работники объектов пользователей',
            },
        ),
    ]
