# Generated by Django 5.2.6 on 2025-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobject',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
