# Generated by Django 5.2.6 on 2025-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_objects', '0002_userobject_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userobject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объект пользователя', 'verbose_name_plural': '01. Объекты пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userobjectdocumentitems',
            options={'verbose_name': 'Элемент документа объекта пользователя', 'verbose_name_plural': '04. Элементы документов объектов пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userobjectdocuments',
            options={'verbose_name': 'Документ объекта пользователя', 'verbose_name_plural': '03. Документы объектов пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userobjectworkers',
            options={'verbose_name': 'Работник объекта пользователя', 'verbose_name_plural': '02. Работники объектов пользователей'},
        ),
        migrations.AddField(
            model_name='userobjectdocuments',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='userobject',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активный'), ('pending', 'Ожидание'), ('completed', 'Завершенный'), ('cancelled', 'Отмененный'), ('on_hold', 'На паузе')], default='active', max_length=255, null=True, verbose_name='Статус объекта'),
        ),
    ]
