# Generated by Django 5.2.6 on 2025-12-02 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_objects', '0003_alter_userobject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userobject',
            index=models.Index(fields=['user', '-created_at'], name='uo_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userobject',
            index=models.Index(fields=['status', '-created_at'], name='uo_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userobject',
            index=models.Index(fields=['is_deleted', '-created_at'], name='uo_deleted_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectdocuments',
            index=models.Index(fields=['user_object', '-created_at'], name='uod_obj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectdocuments',
            index=models.Index(fields=['user', '-created_at'], name='uod_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectworkers',
            index=models.Index(fields=['user_object', 'user'], name='uow_obj_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectworkers',
            index=models.Index(fields=['is_finished'], name='uow_finished_idx'),
        ),
    ]
