# Generated by Django 5.2.6 on 2025-12-02 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created_at'], name='category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteproduct',
            index=models.Index(fields=['user', '-created_at'], name='fp_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteproduct',
            index=models.Index(fields=['product'], name='fp_product_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='product_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_deleted', '-created_at'], name='product_active_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article'], name='product_article_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', '-created_at'], name='pi_product_created_idx'),
        ),
    ]
