# Generated by Django 5.2.6 on 2025-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Обозначает, подтвержден ли email пользователя.', verbose_name='Подтвержден'),
        ),
    ]
