# Generated by Django 5.2.6 on 2025-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartment',
            field=models.CharField(blank=True, help_text='Необязательно. Введите номер квартиры.', max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='Необязательно. Введите ваш город.', max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house',
            field=models.CharField(blank=True, help_text='Необязательно. Введите номер дома.', max_length=50, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_index',
            field=models.CharField(blank=True, help_text='Необязательно. Введите почтовый индекс.', max_length=20, null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, help_text='Необязательно. Введите вашу улицу.', max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
