# Generated by Django 5.2.6 on 2025-10-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_apartment_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_newsletter',
            field=models.BooleanField(default=False, help_text='Подписаться на email рассылку.', verbose_name='Email-рассылка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='special_offers_notifications',
            field=models.BooleanField(default=False, help_text='Получать уведомления о специальных предложениях.', verbose_name='Уведомления о специальных предложениях'),
        ),
    ]
