# Generated by Django 5.2.6 on 2025-10-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_email_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Токен для сброса пароля', max_length=100, null=True, verbose_name='Токен сброса пароля'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время истечения токена'),
        ),
    ]
