# Generated by Django 5.2.6 on 2025-10-28 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_reset_token_and_more'),
        ('website', '0003_alter_contacts_options_alter_serviceitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('finished_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='website.services', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_services', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка услуги',
                'verbose_name_plural': 'Покупки услуг',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'service', 'start_date')},
            },
        ),
    ]
