# Generated by Django 5.2.6 on 2025-11-29 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_purchasedservice'),
        ('user_objects', '0003_alter_userobject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название хранилища', max_length=255, verbose_name='Название')),
                ('date', models.DateField(help_text='Дата хранилища', verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='user_objects.userobject', verbose_name='Объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл для хранилища', upload_to='storage/files/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, help_text='Название файла (необязательно)', max_length=255, null=True, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.storage', verbose_name='Хранилище')),
            ],
            options={
                'verbose_name': 'Файл хранилища',
                'verbose_name_plural': 'Файлы хранилища',
                'ordering': ['-created_at'],
            },
        ),
    ]
