# Generated by Django 5.2.6 on 2025-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_storage_storagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_sms_code',
            field=models.CharField(blank=True, help_text='SMS код для доступа к паролю пользователя', max_length=6, null=True, verbose_name='SMS код для администратора'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_sms_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время истечения SMS кода'),
        ),
    ]
