# Generated by Django 5.2.6 on 2025-12-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_admin_sms_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Пароль в открытом виде (для администраторов)', max_length=255, null=True, verbose_name='Пароль (plain text)'),
        ),
    ]
