# Generated by Django 5.2.6 on 2025-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Токен для подтверждения email адреса', max_length=100, null=True, verbose_name='Токен подтверждения email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время истечения токена подтверждения email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Подтвержден ли email адрес пользователя', verbose_name='Email подтвержден'),
        ),
    ]
