# Generated by Django 5.2.6 on 2025-10-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('why_this_service', models.TextField(blank=True, null=True, verbose_name='Почему эта услуга')),
                ('for_whom', models.TextField(blank=True, null=True, verbose_name='Для кого эта услуга')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент элемента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Элемент услуги',
                'verbose_name_plural': 'Элементы услуг',
                'ordering': ['-created_at'],
            },
        ),
    ]
