# Generated by Django 5.2.6 on 2025-10-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контакты', 'verbose_name_plural': '03. Контакты'},
        ),
        migrations.AlterModelOptions(
            name='serviceitems',
            options={'ordering': ['-created_at'], 'verbose_name': 'Элемент услуги', 'verbose_name_plural': '02. Элементы услуг'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': '01. Услуги'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='map_iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Карта (iframe)'),
        ),
    ]
